# Generated by Django 5.0.6 on 2024-05-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_options_category_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='john@email.com', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Quotation Requests',
            },
        ),
    ]
