# Generated by Django 5.0.6 on 2024-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
    ]
