# Generated by Django 5.0.6 on 2024-05-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTag',
        ),
    ]
