# Generated by Django 5.0.6 on 2024-05-30 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customtag_slug'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtag',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggit.tag'),
        ),
    ]
