# Generated by Django 5.0.6 on 2024-06-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_meta_description_category_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtag',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='customtag',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
